{% set xorg_name = "xtrans" %}
{% set xorg_category = "lib" %}
{% set name = "xorg-" ~ xorg_name %}
{% set version = "1.5.1" %}
{% set sha256 = "dea80fbd8c3c941495b4b1d2785cb652815d016849a0d2ef90d1140de916993e" %}
{% set am_version = "1.16" %} # keep synchronized with build.sh

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://www.x.org/releases/individual/{{ xorg_category }}/{{ xorg_name }}-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - m2-autoconf                   # [win]
    - m2-automake{{ am_version }}   # [win]
    - m2-libtool                    # [win]
    - pkg-config                    # [unix]
    - m2-pkg-config                 # [win]
    - gnuconfig                     # [unix]
    - m2-base                       # [win]
    - make                          # [unix]
    - m2-make                       # [win]
    - {{ compiler("c") }}           # [unix]
    - {{ stdlib("c") }}             # [unix]
    - {{ compiler("m2w64_c") }}     # [win]
    - {{ stdlib("m2w64_c") }}       # [win]
    - autoconf                      # [unix]
    - automake                      # [unix]
    - gettext                       # [unix]
    - libtool                       # [unix]
  host:
    - xorg-util-macros

test:
  commands:

about:
  home: https://www.x.org/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: 'Low-level data transport prototypes for the X.org libraries.'

extra:
  recipe-maintainers:
    - pkgw
