travis:
  secure:
    BINSTAR_TOKEN: jGmXn+YvRuew26vJCxcS4yecG84XQ8be56tU3Kvt6NRTvKqLgNpe8FrH/ybSn86zzDI+CIMw1moEkzdzqU8tfiv0CwDAFxjLjKk7y+pGyCuDAQH3xtX0pwONj81VeLLnPFVE+DgvHVRl7eXz5NoTx+WENmb4gplwHt673mZw6HQG83bok6S1G70r45uNEzAWwh0C1qER4+uOheBAfesiUnh7FqVCXOrjJy2zRBJXihywTZsCWl2ia3tpYhOZJdV7htk1K2nOiW7qxRQFprXfEoXS6HIYi/c6pxZbVW8T2tZ4IO5EP69urwY8iJ3uTj1NdyIfuCYJvInysvgu/nakDrQQeqy9wE6B/UXQO7tvX/l4fTZTYr2StJEMMdJheqB8WJT9mB93PxjhmbnOPZrGp/ZdopHQE66aG22lAfa1S/6AQwPKTcMw3H460kALwCiXTw+ecMDoX24E1INRwR+aBgEZjysqjaHaEgSAo8Ox38AX4GH77Y/ZmbhheLXKMd1Zx/V8YV10dMRtizDNi2p9GsXUwZW7k/KoU2XClqWx3QWt8fmhLCFRTRanuEfqQ3tDBsWKSEhbb4S2sLArYHy1XfjVi577fE9iirCGk9f6+XO3ltEoJhaHqZFso5KoJl/QLRUTlVWoIXqhkGyOTeyAilslpGUITFzhrmyN/NCRefs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
