travis:
  secure:
    BINSTAR_TOKEN: nPspes4wxvo2VFaPP5RnukfTX+0PSX41bOx6TK/iYOPDOfenuAfjrLNUbSW+wZizCWbmLIK5FYXcKr3JbAYYw2zYqDpCgJBHAVvdrIYaKWBx88tXdgFf9OW5/DdF21iIkX2QxZ/sl6hzGUH2YId2kE4pbnxItwKKQjFzs+6kyee1TpAoNDWT7Vwrh/wY2ElWmcpSAkwCB/2WZYhTC8+MU3aT96CLnYg0KbWv3725vAwOUg93Ha6g8JaTp34wYNqjStHTax30g77OKDVBvoh4SFS4J0awzaWzK33HPD7fWojCSPU56ougexmLcYtC5/mCVOCSBAhxBBh3IOWlHS3K/FzB6zBNOlzRV7GJIsG8kV6ww5dO76lSCbVrPILZrVPVJ7CWXMGRjxqfpknRs/T5YWxBjrNHPGOwtMftCnYlldwYKBFhxxaPqGJxlVZeXIlRUTclEqec07e5ZA4va+NJ2rDQ4z3IjBI2tf2uky7ONz+hLrB1/Ns1L76JHJuA/fyVlEg0fAY463NBltpCi4pCG95TGGKyu2evearaf9W3fD7LVOfA03AiwV02XW6QgYZ9YZl+7iWpRdJjskpAbKcIKtmqM9bAdlpjZtVkX+Oe5Dt49pPn/NBBUdlXkWRzsBrKDjAW5K0di0Y1FVEsuiYO6TStSHZpg1gW0YXuUOM3ViU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
