travis:
  secure:
    BINSTAR_TOKEN: PWRHDKV2NFGjfSktotIhK6plKmv42WKz9BSje67QGHaZ0ukdpbKpUe3fkNwtg1TjGwCq36s6XpFR+0ziArG/yJ8ZZad7iVMQtD6eUQT5UAAg2jUAC90B247RAQUo6Tkk9dZVauZm+ZBbmYaiqNkouaXUmvTABKEb6cEMWE17LiQhULQDII20f8BMlCh3d7SKB8KEMw2hoMtIK4SzRWrCl/FCSUFW3SOJaMVitmFij5njYNZwUmf7mh3RmpjjH/FD8J1hvr/bMVzrMIhoXGFOSKkw9cRe6jQ3VGagdtcJRrf6n6usKw7yJn4WJ58dYadfZ0vqMqKRYT1sSRpVWs73eBt9RzNH8ndyhn35NFBki2WOjB/j+2KAh5vextStyDPovWrOkW4EmZ7rNYUend5cxWYRoiDNjAVIKLzh7+wgjNYSc7Oroq5gjKFvM326wNVqgg4IVMhOlrBvJ2Asi0g4sZkobyJbnY4TndByNs4/lSvGyLTBLlAPXVaeKw8Y2woLono59LZDya74A0H1fYGhXH0pQMBfasctIgf1Vkziq8k7E/kyDwFJJXa0MiRd2krdSRaJbhWpwjig8SCxt6pJxx19cUrjClVqv3Mjdm0x8xKtVVyJvOGVnBRc/boqnuLxyw790MzpeCTBYp0Y8kVVHhW2E+66MoKBUw4dSAA/qCw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
